// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package injector

import (
	"product-api-go/internal/database"
	"product-api-go/internal/handler/category"
	"product-api-go/internal/handler/measurement"
	"product-api-go/internal/handler/product"
	category2 "product-api-go/internal/repository/postgres/category"
	measurement2 "product-api-go/internal/repository/postgres/measurement"
	product2 "product-api-go/internal/repository/postgres/product"
	category3 "product-api-go/internal/repository/redis/category"
	measurement3 "product-api-go/internal/repository/redis/measurement"
	product3 "product-api-go/internal/repository/redis/product"
)

// Injectors from category_wire.go:

func InitializedCategoriesModule() *category.CategoriesController {
	db := database.InitDatabase()
	categoriesPostgres := category2.NewCategoriesPostgres(db)
	client := database.InitRedis()
	categoriesRedis := category3.NewCategoriesRedis(client)
	categoriesService := category.NewCategoriesService(categoriesPostgres, categoriesRedis)
	categoriesController := category.NewCategoriesController(categoriesService)
	return categoriesController
}

// Injectors from measurement_wire.go:

func InitializedMeasurementsModule() *measurement.MeasurementsController {
	db := database.InitDatabase()
	measurementsPostgres := measurement2.NewMeasurementsPostgres(db)
	client := database.InitRedis()
	measurementsRedis := measurement3.NewMeasurementsRedis(client)
	measurementsService := measurement.NewMeasurementsService(measurementsPostgres, measurementsRedis)
	measurementsController := measurement.NewMeasurementsController(measurementsService)
	return measurementsController
}

// Injectors from product_wire.go:

func InitializedProductsModule() *product.ProductsController {
	db := database.InitDatabase()
	productsPostgres := product2.NewProductsPostgres(db)
	client := database.InitRedis()
	productsRedis := product3.NewProductsRedis(client)
	measurementsPostgres := measurement2.NewMeasurementsPostgres(db)
	categoriesPostgres := category2.NewCategoriesPostgres(db)
	productsService := product.NewProductsService(productsPostgres, productsRedis, measurementsPostgres, categoriesPostgres)
	productsController := product.NewProductsController(productsService)
	return productsController
}
